### ISSUE TITLE
How to install this exactly?

### ISSUE THREAD

**Issue by sutidor** [esimonetti/toothpaste#1]
If I git clone first, composer gives me 
`[UnexpectedValueException]
Could not parse version constraint LICENSE: Invalid version string "LICENSE"`

If I dont 
`[InvalidArgumentException]
Package esimonetti/toothpaste at version * has a PHP requirement incompatible with your PHP version (5.6.0)`

(although php -v gives me 7.3)
System:
Debian 9 with Plesk installed.

Any help appreciated, thanks in advance

**Comment by esimonetti** [comment]
Hi there,

I have never seen that issue actually. What exact steps do you take to install it? Have you tried on SugarDockerized as well?

Could you attempt to only leverage composer (packagist), instead of cloning the repository? Does it make any difference? `composer require esimonetti/toothpaste dev-master`

**Comment by sutidor** [comment]
Hey, 

I think I cannot take advantage of it anyways, as I'm using SuiteCRM, right? For some reason I found your package and it seemed very useful (and overread it was for Sugar only). Thanks for your help!
